config/routes.rb
DentalHygiene::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/signup',    to: 'users#new',    via: 'get'
  match '/signin',    to: 'sessions#new', via: 'get'
  match '/signout',   to: 'sessions#destroy', via: 'delete'
  match '/services',    to: 'static_pages#services',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/testimonials', to: 'static_pages#testimonials', via: 'get'
  match '/mouthguards', to:  'static_pages#mouthguards', via: 'get'
  match '/whitening_trays', to:  'static_pages#whitening_trays', via: 'get'
  match '/scaling', to: 'static_pages#scaling', via: 'get'
  match '/polishing', to: 'static_pages#polishing', via: 'get'
  match '/gumassessment', to: 'static_pages#gumassessment', via: 'get'
  match '/fluoride', to: 'static_pages#fluoride', via: 'get'
  match '/oralexamination', to: 'static_pages#oralexamination', via: 'get'
  match '/cancerscreening', to: 'static_pages#cancerscreening', via: 'get'
  match '/denturecleaning', to: 'static_pages#denturecleaning', via: 'get'
  match '/referrals', to: 'static_pages#referrals', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
		    format: { with: VALID_EMAIL_REGEX },
		    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
  
  def services
  end
 
  def testimonials
  end

  def mouthguards
  end

  def whitening_trays
  end

  def scaling
  end

  def polishing
  end

  def gumassessment
  end
  
  def fluoride
  end

  def oralexamination
  end

  def cancerscreening
  end
  
  def denturecleaning
  end

  def referrals
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.

  def full_title(page_title)
    base_title = "Dental Hygiene on the Move"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<br>

<div id="footer">
  
  <div class = "container">
    <div class="row">
      <div class="col-sm-4 textSizeOverride2">
        
        
	<%= link_to "About", about_path %></li>&nbsp;|&nbsp;
	<%= link_to "Services", services_path %></li>&nbsp;|&nbsp;
	<%= link_to "Contact", contact_path %></li>
      </div>
			  
      <div class="col-sm-4 customOverride">
        <p>Connect with us on Facebook!</p>
	  <p>
	  <a href="https://www.facebook.com/pages/Dental-Hygiene-on-the-Move/261016656970"><img width='10%' src="/assets/facebook.png" alt=""></a>
	  <br>
	  <br>
	  &copy Dental Hygiene on the Move 2013
	  </p>   

      </div>
      <div class="col-sm-4 textSizeOverride2 customOverride ">
        275 Bradley Street | Haileybury, ON | P0J 1K0<br />
	(705) 648-3740 | <a href="mailto:kari.flaxey@gmail.com"> kari.flaxey@gmail.com
      </div>
    </div>

</div>  
</div>		 

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row titleOverride">
    <h1>Dental Hygiene on the Move</h1><br>
    <br>
  </div>
  <div class="navbar  textOverride navOverride navOverride5">
    <div class="navbar-inner">
      <ul class="nav nav-tabs  nav-justified  navOverride2 navOverride3 navOverride4 navOverride6 ">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>

        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>

        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
        <li class="<%= 'active' if current_page?(services_path) %>"><%= link_to "Services", services_path %></li>
       <li class="<%= 'active' if current_page?(testimonials_path) %>"><%= link_to "Testimonials", testimonials_path %></li>

       <% if signed_in? %>
         <li><%= link_to "Users", '#' %></li>
         <li id="dropdownMenu" class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Account <b class="caret"></b>
           </a>
           <ul class="dropdown-menu pull-right">
             <li><%= link_to "Profile", current_user %></li>
             <li><%= link_to "Settings", '#' %></li>
             <li class="divider"></li>
             <li>
               <%= link_to "Sign out", signout_path, method: "delete" %>
             </li>
           </ul>
         </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/layouts/_jqueryjavascript.html.erb
<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>

		
<script>
$(function(){
  $("#myCarousel").carousel('cycle');
});
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheets.html.erb
<meta charset="utf-8">
    <title>My First Bootstrap project</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.css">
    <link href="http://fonts.googleapis.com/css?family=Dancing Script" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin Sans" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="base.css">
    <link rel="stylesheet" href="less/mixins.less">
	
    <style> 
    body { 
      padding-top: 70px;
      padding-bottom: 50px;
    } 
    </style> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/stylesheets' %>
    <%= render 'layouts/jqueryjavascript' %>

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", 
					   "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |key,value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_servicessidebar.html.erb
<div class="col-sm-4 sideborderOverride ">
  <div class="well sidebar-nav ">
    <ul class="nav">
      <li><p>Services</p></li>
      <li class="active"><%= link_to "Mouthguards", mouthguards_path %></li>
      <li><%= link_to "Whitening Trays", whitening_trays_path %></li>
      <br>
      <li><p>Mobile Professional Dental Cleaning Includes:</p></li>
      <li><%= link_to "Scaling", scaling_path %></li>
      <li><%= link_to "Polishing", polishing_path %></li>
      <li><%= link_to "Gum Assessment", gumassessment_path %></li>
      <li><%= link_to "Fluoride", fluoride_path %></li>
      <li><%= link_to "Intra/Extra Oral Examination", oralexamination_path %></li>
      <li><%= link_to "Oral Cancer Screening", cancerscreening_path %></li>
      <li><%= link_to "Denture Cleaning", denturecleaning_path %></li>
      <li><%= link_to "Referrals to other healthcare professionals", referrals_path %></li>
    </ul>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'Kari Flaxey') %>
<div class="container">
<div class="row">
		  <div class="col-md-6">
		    <p><img width="550" height="500" src="http://media.merchantcircle.com/5116226/Dentist-Oklahoma-City_full.jpeg" alt = "" />
		  </div>
		  <div class="col-md-6">
		    <h2>Kari Flaxey</h2>
			Registered Dental Hygienist<br>
			<br>
			Kari graduated with honours from Canadore College in North Bay in 2007.  She began practicing in her home town of 
			New Liskeard at a local Dentist office for 5 years which included orthodontics before moving to the local health unit 
			where she is currently employed.<br>
			<br>
			Dental Hygiene on the Move originated by Kari's motivation to do something different.  With limited public
			transportation and several rural areas surrounding New Liskeard, it was difficult for some families to get 
			to the local dentist offices.  Kari wanted to give everyone in the area an opportunity to receive proper 
			dental hygiene regardless of their location.  With the support of the community and her current employer at 
			the same, Kari launched Dental Hygiene on the Move.   Although it was something new to the area, Kari thought 
			it would benefit alot of people and she was determined to make it a success.
		    <br>
			<br>
			<br>
			
		  </div>
		</div> 
</div> 		 

app/views/static_pages/cancerscreening.html.erb
<% provide(:title, 'Oral Cancer Screening') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
  <div class="col-sm-8 text-center colOverride-sm-8  ">
  
  <h2>Oral Cancer Screening</h2>
  <br>
  Available in the Fall of 2014!
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class = "container">
  <div class="row">
    <div class="col-sm-6 customOverride">
      <br>
      <iframe width="625" height="550" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=275+Bradley+St,+Temiskaming+Shores,+ON,+Canada&amp;aq=0&amp;oq=275+Bradl&amp;sll=40.697488,-73.979681&amp;sspn=0.958918,2.113495&amp;ie=UTF8&amp;hq=&amp;hnear=275+Bradley+St,+Temiskaming+Shores,+Timiskaming+District,+Ontario+P0J+1K0,+Canada&amp;t=m&amp;z=14&amp;ll=47.443418,-79.629761&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=275+Bradley+St,+Temiskaming+Shores,+ON,+Canada&amp;aq=0&amp;oq=275+Bradl&amp;sll=40.697488,-73.979681&amp;sspn=0.958918,2.113495&amp;ie=UTF8&amp;hq=&amp;hnear=275+Bradley+St,+Temiskaming+Shores,+Timiskaming+District,+Ontario+P0J+1K0,+Canada&amp;t=m&amp;z=14&amp;ll=47.443418,-79.629761" style="color:#0000FF;text-align:left">View Larger Map</a></small>		  
    </div>
    <div class="col-sm-6 customOverride social img">
      
      
      <br>
      <b>Dental Hygiene on the Move</b>
      <address>
      275 Bradley Street<br>
      Haileybury, ON<br>
      P0J 1K0<br>
      <br>
      <abbr title="Phone">P:</abbr> 705 648 3740<br>
      <abbr email="Email">E:</abbr> kari.flaxey@gmail.com<br>
      </address>
    </div>
  </div>
</div>

app/views/static_pages/fluoride.html.erb
<% provide(:title, 'Fluoride') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
  <div class="col-sm-8 text-center colOverride-sm-8  ">
  Available in the Fall of 2014!
  </div>
</div>

app/views/static_pages/gumassessment.html.erb
<% provide(:title, 'Gum Assessment') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
  <div class="col-sm-8 text-center colOverride-sm-8  ">
  Available in the Fall of 2014!
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row">
     <div class="col-sm-8">
       <div id="carousel-example-generic" class="carousel slide pull-left" style="width: 100%;  margin: 0 auto">
       
       <!-- Wrapper for slides -->
       <div class="carousel-inner">
	 <div class="active item">
	   <img src="/assets/shel.jpg"/>
	     <div class="container">
		<div class="carousel-caption">
		  <h2>Keep your smile white!<h2>
		</div>
	     </div>
	 </div>

         <div class="item">
	   <img width="100%" src="/assets/matt2.jpg"/>
	   <div class="container">
	     <div class="carousel-caption">
	       <h2>Don't forget to floss!<h2>
	     </div>
	   </div>
         </div>
       
         <div class="item">
	   <img width="100%" height="100%" src="/assets/bigsmile.jpg"/>
	     <div class="container">
	       <div class="carousel-caption">
	         <h2>Brush at least twice a day!<h2>
	       </div>
	     </div>
        </div>
      </div>
	
      <!-- Controls -->
      <a class="carousel-control left carouselControlOverride" href="#carousel-example-generic" data-slide="prev">
        <span class="icon-prev"></span>
      </a>
   
      <a class="carousel-control right" href="#carousel-example-generic" data-slide="next">
        <span class="icon-next"></span>
      </a>
      </div>
    </div>
		  
		  <div class="col-sm-4">
		    <p>Dental Hygiene on the Move takes pride in being a unique kind of dental service - one that makes your experience both 
			comfortable and convenient.  They provide their patients with up-to-date treatment options to create optimum dental health and beauty.<br>
			<br>			
			We know each patient has their own individual needs and we are committed to accomplishing this by thoroughly discussing treatment options 
			available to each patient.  From custom sports mouth guards to perfecting smiles with custom made whitening kits, Dental Hygiene on the Move 
			will work with you to make sure you have the best possible service.</p>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary " %>
		  </div>
		</div>
		<br>
		<div class="row">
		  <div class="col-sm-8 customOverride">
		    <p><b>Currently taking appointments for:</b></p>
		  </div>
		</div>
		<br>
		
		
		<div class="row ">
		  <div class="col-sm-4 customOverride  ">
		    <%= link_to "Custom Fit Whitening Kits", whitening_trays_path, :class => "btn btn-default " %>
		    <br>
		    <br>
		    <img width="100%" height="265" src="/assets/whitening.jpg"/>
			
		  </div>
		  
		  <div class="col-sm-4 customOverride">
		    <%= link_to "Custom Sports Mouth Guards", mouthguards_path, :class => "btn btn-default " %>
		    <br>
		    <br>
		    <img width="100%" height="265" src="https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-ash3/p480x480/68673_621543197868811_1375200847_n.jpg"/>
		  </div>
		  
		  <div class="col-sm-4 customOverride">
		    <p>Come visit us!</p>
			
				
			<br>
		    <iframe width="100%" height="265" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=275+Bradley+St,+Temiskaming+Shores,+ON,+Canada&amp;aq=0&amp;oq=275+Bradl&amp;sll=40.697488,-73.979681&amp;sspn=0.958918,2.113495&amp;ie=UTF8&amp;hq=&amp;hnear=275+Bradley+St,+Temiskaming+Shores,+Timiskaming+District,+Ontario+P0J+1K0,+Canada&amp;t=m&amp;z=14&amp;ll=47.443418,-79.629761&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=275+Bradley+St,+Temiskaming+Shores,+ON,+Canada&amp;aq=0&amp;oq=275+Bradl&amp;sll=40.697488,-73.979681&amp;sspn=0.958918,2.113495&amp;ie=UTF8&amp;hq=&amp;hnear=275+Bradley+St,+Temiskaming+Shores,+Timiskaming+District,+Ontario+P0J+1K0,+Canada&amp;t=m&amp;z=14&amp;ll=47.443418,-79.629761" style="color:#0000FF;text-align:left"></a></small>	
		  </div>
		</div>
		
		
		
	 </div> 
</div>

app/views/static_pages/mouthguards.html.erb
<% provide(:title, 'Custom Sports Mouth Guards') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %> 
		
  <div class="col-sm-8 ">
    <p><b>Why use a custom Mouth Guard?</b></p>
		  
		  The purpose of the sports mouth guard is to act as a shock absorber in the mouth to protect the teeth
		  from excessive forces.  The mouth guard also protects your head and brain from concussion if the blow is onto
		  the lower jaw.<br>
		  <br>
		  
		  Well made mouth guards adapt smoothly to the upper teeth and gums, staying firmly in place, even when speaking,
		  breathing heavily or playing sports very actively.<br>
		  <br>
		  <p><b>The Procedure</b></p>
		  
		  A custom mouth guard procedure is very quick and lasts approximately 10 minutes. The dental Hygienist will take 
		  an upper impression, you will choose the color of your mouth guard and it will be ready in approximately one week.
		  Dental Hygiene on the move offers a variety of colors for all ages.<br>
		  <br>
		  <p><b>Cost</b></p>
		  
		   $40.00 - Per Mouth Guard<br>
		  <br>
		  
  </div>
  <div id ="myCarousel" class="carousel slide col-sm-8 " >
    <div class="carousel-inner ">
      <div class="active item">
        <div class="col-sm-6">
          <img width="350" height="300" src="/assets/mouthguards2.jpg" alt="">
        </div>
        <div class="col-sm-4">
          <img src="http://placehold.it/350x300" alt="">
        </div>
      </div>
      <div class="item">
        <div class="col-sm-6">
          <img src="http://placehold.it/350x300" alt="">
        </div>
        <div class="col-sm-4">
          <img src="http://placehold.it/350x300" alt="">
        </div>
      </div>
    </div>
    <a class="carousel-control left carouselControlOverride" href="#myCarousel" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">
      <span class="icon-next"></span>
    </a>
        
  </div>
</div>

app/views/static_pages/oralexamination.html.erb
<% provide(:title, 'Intra/Extra Oral Examination') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
  <div class="col-sm-8 text-center colOverride-sm-8  ">
  Available in the Fall of 2014!
  </div>
</div>

app/views/static_pages/polishing.html.erb
<% provide(:title, 'Polishing') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
  <div class="col-sm-8 text-center colOverride-sm-8  ">
  Available in the Fall of 2014!
  </div>
</div>

app/views/static_pages/scaling.html.erb
<% provide(:title, 'Scaling') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
  <div class="col-sm-8 text-center colOverride-sm-8  ">
  Available in the Fall of 2014!
  </div>
</div>

app/views/static_pages/services.html.erb
<% provide(:title, 'Services') %>
<div class = "container">
<%= render 'static_pages/servicessidebar' %>
<div class="col-sm-8 customOverride">
  <br>
  <p>Dental Hygiene on the Move provides a full line of services for all of your dental needs. Whether its a custom sports mouth guard or a teeth cleaning, we pride ourselves on being up-to-date with the latest technology and our focus on making you, the patient, always feel comfortable. Please click on any of the services to your left to learn more and please note that we do follow the Ontario Hygiene fee guide.</p>
  <p>Currently Kari is offering Custom Sports Mouth Guard and the custom whitening trays and take-home kits. 
     At this time she is accepting day, evening and weekends appointments and will travel between Kirkland Lake and Temagami.  If you're not certain that your area is within the travel limitations, please contact Kari and she will gladly assess whether she is able to come to you.</p>
  <p>The Mobile professional dental cleaning will only be available in the fall of 2014. The exact date will be announced when it has been decided.</p>
  <br>
  <p><b><h2>Dental Insurance Plans are accepted!</h2></b></p>
  <br>
  <img width="300" height="300" src="/assets/mav.jpg"/>
  <img width="300" height="300" src="/assets/inaction.jpg"/>
  
</div>
</div>

app/views/static_pages/testimonials.html.erb
<% provide(:title, 'What People Are Saying About Us!') %>
<div class="container">
  <div class="row customOverride">
    <h2>What People Are Saying About Us!</h2>
    <br>
    <br>
    <div class="col-md-4">
      <div class="triangle-isosceles">
        <p><i>"Kari is extremely professional and is excellent at what she does!
	     My teeth have never been whiter!"</i></p>
        <b><i>Laurie Walroth</i></b>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/static_pages/whitening_trays.html.erb
<% provide(:title, 'Whitening Trays') %>
<div class= "container">
<%= render 'static_pages/servicessidebar' %>
<div class="col-sm-8 ">
		  <p><b>Custom Made Whitening Trays</b></p>
		  <p>Dental Hygiene on the move offers custom made whitening trays for a visibly whiter 
		  smile in one day and your whitest healthiest smile in seven to fourteen days. For the 
		  prodecure Kari uses Philips Zoom which are the only at-home whitening products to contain 
		  amorphous calcium phosphate (ACP), which is clinically proven to reduce sensitivity, protect 
		  enamel and help improve the luster and smoothness of the teeth.</p>
		  
		  <p>Kari will create a custom tray made just for you and will tailor the formula concentration 
		  and wear times to your sensitivity and lifestyle.</p>
		  <br>
		  <p><b>Difference between store bought and professional whitening trays?</b></p>
		  
		  Store bought bleaching kits do not include a good custom fitted tray. They use a standard one-size fits all tray,
		  whereas the ones Dental Hygiene on the Move provides to you are custom fitted to your teeth. Because of this, the bleaching
		  process takes longer and is less effective.<br>
          <br>
		 		  
		</div>
	  
	  
	  <div id ="myCarousel" class="carousel slide col-sm-8 " >
	    
	    
		<div class="carousel-inner ">
		  <div class="active item">
            <div class="col-sm-6">
              <img width="350" height="300" src="/assets/whitening.jpg" alt="">
            </div>
            <div class="col-sm-4">
              <img width="350" height="300" src="http://www.teethwhiteningathome.com/wp-content/uploads/2013/01/white-teeth.jpg" alt="">
            </div>
          </div>
          <div class="item">
            <div class="col-sm-6">
              <img width="350" height="300" src="/assets/zoomb&a.jpg" alt="">
            </div>
            <div class="col-sm-4">
              <img width="350" height="300" src="/assets/zoom.jpg" alt="">
            </div>
          </div>
        </div>
		 <a class="carousel-control left carouselControlOverride" href="#myCarousel" data-slide="prev">
		   <span class="icon-prev"></span>
		 </a>
		 <a class="carousel-control right" href="#myCarousel" data-slide="next">
		   <span class="icon-next"></span>
		 </a>
        
       </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>


<div class="row">
  <div class="col 6 offset3">
  <div class= "container customOverride">
    <h2>Sign up</h2>
    <br>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
 
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
      <br>

      <%= f.label :email %>
      <br>
      <%= f.text_field :email %>
      <br>

      <%= f.label :password %>
      <br>
      <%= f.password_field :password %>
      <br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <br>
      <%= f.password_field :password_confirmation %>
      <br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  
  <%= @user.name %>
</h1>